version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Disables all linters by default, so we can explicitly enable the ones we want.
  default: none
  enable:
    # --- Core Linters (Highly Recommended) ---
    - bodyclose
    - dupl
    - errcheck
    # - exportloopref # Removed: Not supported by your golangci-lint version
    # --- Style & Formatting Linters ---
    - goconst
    - gocritic
    - gocyclo
    # - gosimple      # Removed: Not supported by your golangci-lint version
    - govet
    # --- Complexity & Maintainability ---
    - funlen
    - ineffassign
    - misspell
    - revive
    - staticcheck
    # - stylecheck    # Removed: Not supported by your golangci-lint version
    - unconvert
    - unused
    - whitespace

  # Settings for specific linters are nested under linters.settings.
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    funlen:
      lines: 100
      statements: 50

  # Exclusions are now configured under linters.exclusions.
  exclusions:
    rules:
      # Exclude some linters from running on test files.
      - path: _test\.go
        linters:
          - dupl
          - gocritic
          - funlen
          - errcheck
          - goconst

formatters:
  settings:
    goimports:
      # Group local imports separately. This is a best practice.
      local-prefixes:
        - github.com/goexts/generic