blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Share an Idea
    url: https://github.com/goexts/generic/discussions/new
    about: Please use GitHub Discussions for questions, ideas, and general conversation.