// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from strings.go.

// Package strings contains generated code by adptool.
package strings

import (
	"iter"
	strings "strings"
	"unicode"
)

type (
	Builder  = strings.Builder
	Reader   = strings.Reader
	Replacer = strings.Replacer
)

func Clone(s string) string {
	return strings.Clone(s)
}

func Compare(a, b string) int {
	return strings.Compare(a, b)
}

func Contains(s, substr string) bool {
	return strings.Contains(s, substr)
}

func ContainsAny(s, chars string) bool {
	return strings.ContainsAny(s, chars)
}

func ContainsFunc(s string, f func(rune) bool) bool {
	return strings.ContainsFunc(s, f)
}

func ContainsRune(s string, r rune) bool {
	return strings.ContainsRune(s, r)
}

func Count(s, substr string) int {
	return strings.Count(s, substr)
}

func Cut(s, sep string) (before, after string, found bool) {
	return strings.Cut(s, sep)
}

func CutPrefix(s, prefix string) (after string, found bool) {
	return strings.CutPrefix(s, prefix)
}

func CutSuffix(s, suffix string) (before string, found bool) {
	return strings.CutSuffix(s, suffix)
}

func EqualFold(s, t string) bool {
	return strings.EqualFold(s, t)
}

func Fields(s string) []string {
	return strings.Fields(s)
}

func FieldsFunc(s string, f func(rune) bool) []string {
	return strings.FieldsFunc(s, f)
}

func FieldsFuncSeq(s string, f func(rune) bool) iter.Seq[string] {
	return strings.FieldsFuncSeq(s, f)
}

func FieldsSeq(s string) iter.Seq[string] {
	return strings.FieldsSeq(s)
}

func HasPrefix(s, prefix string) bool {
	return strings.HasPrefix(s, prefix)
}

func HasSuffix(s, suffix string) bool {
	return strings.HasSuffix(s, suffix)
}

func Index(s, substr string) int {
	return strings.Index(s, substr)
}

func IndexAny(s, chars string) int {
	return strings.IndexAny(s, chars)
}

func IndexByte(s string, c byte) int {
	return strings.IndexByte(s, c)
}

func IndexFunc(s string, f func(rune) bool) int {
	return strings.IndexFunc(s, f)
}

func IndexRune(s string, r rune) int {
	return strings.IndexRune(s, r)
}

func Join(elems []string, sep string) string {
	return strings.Join(elems, sep)
}

func LastIndex(s, substr string) int {
	return strings.LastIndex(s, substr)
}

func LastIndexAny(s, chars string) int {
	return strings.LastIndexAny(s, chars)
}

func LastIndexByte(s string, c byte) int {
	return strings.LastIndexByte(s, c)
}

func LastIndexFunc(s string, f func(rune) bool) int {
	return strings.LastIndexFunc(s, f)
}

func Lines(s string) iter.Seq[string] {
	return strings.Lines(s)
}

func Map(mapping func(rune) rune, s string) string {
	return strings.Map(mapping, s)
}

func NewReader(s string) *strings.Reader {
	return strings.NewReader(s)
}

func NewReplacer(oldnew ...string) *strings.Replacer {
	return strings.NewReplacer(oldnew...)
}

func Repeat(s string, count int) string {
	return strings.Repeat(s, count)
}

func Replace(s, old, new string, n int) string {
	return strings.Replace(s, old, new, n)
}

func ReplaceAll(s, old, new string) string {
	return strings.ReplaceAll(s, old, new)
}

func Split(s, sep string) []string {
	return strings.Split(s, sep)
}

func SplitAfter(s, sep string) []string {
	return strings.SplitAfter(s, sep)
}

func SplitAfterN(s, sep string, n int) []string {
	return strings.SplitAfterN(s, sep, n)
}

func SplitAfterSeq(s, sep string) iter.Seq[string] {
	return strings.SplitAfterSeq(s, sep)
}

func SplitN(s, sep string, n int) []string {
	return strings.SplitN(s, sep, n)
}

func SplitSeq(s, sep string) iter.Seq[string] {
	return strings.SplitSeq(s, sep)
}

func Title(s string) string {
	return strings.Title(s)
}

func ToLower(s string) string {
	return strings.ToLower(s)
}

func ToLowerSpecial(c unicode.SpecialCase, s string) string {
	return strings.ToLowerSpecial(c, s)
}

func ToTitle(s string) string {
	return strings.ToTitle(s)
}

func ToTitleSpecial(c unicode.SpecialCase, s string) string {
	return strings.ToTitleSpecial(c, s)
}

func ToUpper(s string) string {
	return strings.ToUpper(s)
}

func ToUpperSpecial(c unicode.SpecialCase, s string) string {
	return strings.ToUpperSpecial(c, s)
}

func ToValidUTF8(s, replacement string) string {
	return strings.ToValidUTF8(s, replacement)
}

func Trim(s, cutset string) string {
	return strings.Trim(s, cutset)
}

func TrimFunc(s string, f func(rune) bool) string {
	return strings.TrimFunc(s, f)
}

func TrimLeft(s, cutset string) string {
	return strings.TrimLeft(s, cutset)
}

func TrimLeftFunc(s string, f func(rune) bool) string {
	return strings.TrimLeftFunc(s, f)
}

func TrimPrefix(s, prefix string) string {
	return strings.TrimPrefix(s, prefix)
}

func TrimRight(s, cutset string) string {
	return strings.TrimRight(s, cutset)
}

func TrimRightFunc(s string, f func(rune) bool) string {
	return strings.TrimRightFunc(s, f)
}

func TrimSpace(s string) string {
	return strings.TrimSpace(s)
}

func TrimSuffix(s, suffix string) string {
	return strings.TrimSuffix(s, suffix)
}
