// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from maps.go.

// Package maps contains generated code by adptool.
package maps

import (
	maps "golang.org/x/exp/maps"
)

func Clear[M ~map[K]V, K comparable, V any](m M) {
	maps.Clear[M, K, V](m)
}

func Clone[M ~map[K]V, K comparable, V any](m M) M {
	return maps.Clone[M, K, V](m)
}

func Copy[M1 ~map[K]V, M2 ~map[K]V, K comparable, V any](dst M1, src M2) {
	maps.Copy[M1, M2, K, V](dst, src)
}

func DeleteFunc[M ~map[K]V, K comparable, V any](m M, del func(K, V) bool) {
	maps.DeleteFunc[M, K, V](m, del)
}

func Equal[M1, M2 ~map[K]V, K, V comparable](m1 M1, m2 M2) bool {
	return maps.Equal[M1, M2, K, V](m1, m2)
}

func EqualFunc[M1 ~map[K]V1, M2 ~map[K]V2, K comparable, V1, V2 any](m1 M1, m2 M2, eq func(V1, V2) bool) bool {
	return maps.EqualFunc[M1, M2, K, V1, V2](m1, m2, eq)
}

func Keys[M ~map[K]V, K comparable, V any](m M) []K {
	return maps.Keys[M, K, V](m)
}

func Values[M ~map[K]V, K comparable, V any](m M) []V {
	return maps.Values[M, K, V](m)
}
