// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from cmp.go.

// Package cmp contains generated code by adptool.
package cmp

import (
	cmp "cmp"
)

type Ordered = cmp.Ordered

func Compare[T cmp.Ordered](x, y T) int {
	return cmp.Compare[T](x, y)
}

func Less[T cmp.Ordered](x, y T) bool {
	return cmp.Less[T](x, y)
}

func Or[T comparable](vals ...T) T {
	return cmp.Or[T](vals...)
}
