name: Test and Release

# This workflow runs on every push to the main branch.
# It always runs tests. A release is only triggered if the commit message
# contains the string "[release]".
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23.x'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Use a specific v2 version of golangci-lint
          version: v2.4.0
          # The action will automatically use .golangci.yml from the repository root
          working-directory: .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.23.0' # The Go version to download (if necessary) and use.

      - name: Run tests
        run: make test

  release:
    # The release job depends on the test job succeeding.
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release and Changelog
        # This action automates the entire release process based on
        # Conventional Commit messages.
        uses: googleapis/release-please-action@v3
        with:
          # The release-type for a standard Go module.
          # It automatically finds the go.mod file, reads the module path,
          # and creates tags like `v1.2.3`.
          release-type: go
          # The token is required for release-please to create releases.
          token: ${{ secrets.GITHUB_TOKEN }}
