name: Test and Release

# This workflow runs on every push to the main branch.
# It always runs tests. A release is only triggered if the commit message
# contains the string "[release]".
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Use the Go version from go.mod for reproducible builds
          go-version: '1.23.x'

      - name: Run tests
        run: go test -v ./...

  release:
    # The release job depends on the test job succeeding.
    needs: [test]
    # It only runs on the main branch and if the commit message includes "[release]".
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - name: Create Release and Changelog
        # This action automates the entire release process based on
        # Conventional Commit messages.
        uses: google-github-actions/release-please-action@v4
        with:
          # The release-type for a standard Go module.
          # It automatically finds the go.mod file, reads the module path,
          # and creates tags like `v1.2.3`.
          release-type: go
          # The token is required for release-please to create releases.
          token: ${{ secrets.GITHUB_TOKEN }}
