// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from runes.go.

// Package runes contains generated code by adptool.
package runes

import (
	"unicode"

	runes "golang.org/x/text/runes"
	"golang.org/x/text/transform"
)

type (
	Set         = runes.Set
	Transformer = runes.Transformer
)

func If(s runes.Set, tIn, tNotIn transform.Transformer) runes.Transformer {
	return runes.If(s, tIn, tNotIn)
}

func In(rt *unicode.RangeTable) runes.Set {
	return runes.In(rt)
}

func Map(mapping func(rune) rune) runes.Transformer {
	return runes.Map(mapping)
}

func NotIn(rt *unicode.RangeTable) runes.Set {
	return runes.NotIn(rt)
}

func Predicate(f func(rune) bool) runes.Set {
	return runes.Predicate(f)
}

func Remove(s runes.Set) runes.Transformer {
	return runes.Remove(s)
}

func ReplaceIllFormed() runes.Transformer {
	return runes.ReplaceIllFormed()
}
